version: '3'
services:

  postgres:
    image: postgres:17
    container_name: im_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fim_server_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/datadir:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.4-alpine
    container_name: im_redis
    restart: always
    ports:
      - "6379:6379"

  etcd:
    image: bitnami/etcd:3.5.19
    container_name: im_etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: im_zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.9
    container_name: im_kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    depends_on:
      - zookeeper

  kafka-map:
    image: dushixiang/kafka-map:latest
    container_name: im_kafka_map
    restart: always
    ports:
      - "9001:8080"
    environment:
      - DEFAULT_USERNAME=admin
      - DEFAULT_PASSWORD=admin
