Name: settingsrpc.rpc
ListenOn: 0.0.0.0:20055
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: settingsrpc.rpc
Database:
  DataSource: host=127.0.0.1 user=root password=root dbname=fim_server_db port=5432 sslmode=disable TimeZone=Asia/Shanghai