Name: settingsrpc.rpc
ListenOn: 0.0.0.0:20055
Etcd:
  Hosts:
  - 192.168.80.3:2379
  Key: settingsrpc.rpc
Mysql:
  DataSource: root:root@tcp(127.0.0.1:3306)/fim_server_db?charset=utf8mb4&parseTime=True&loc=Local