version: '3'
services:

  postgres:
    image: postgres:17
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fim_server_db
    volumes:
      - ./postgres/datadir:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.4-alpine
    restart: always
    network_mode: host

  etcd:
    image: bitnami/etcd:3.5.19
    network_mode: host
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379

  zookeeper:
    image: bitnami/zookeeper:3.9
    restart: always
    network_mode: host
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.9
    restart: always
    network_mode: host
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=127.0.0.1:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    depends_on:
      - zookeeper

  kafka-map:
    image: dushixiang/kafka-map:latest
    restart: always
    network_mode: host
    environment:
      - DEFAULT_USERNAME=admin
      - DEFAULT_PASSWORD=admin
      - SERVER_PORT=9001

  gateway:
    build:
      context: fim_gateway
    restart: always
    network_mode: host
    volumes:
      - ./fim_gateway/gateway.yaml:/app/gateway.yaml

  auth_api:
    build:
      context: fim_auth/auth_api
    restart: always
    network_mode: host
    volumes:
      - ./fim_auth/auth_api/auth.yaml:/app/auth.yaml
    depends_on:
      - postgres
      - redis
      - user_rpc
      - settings_api
      - kafka

  chat_api:
    build:
      context: fim_chat/chat_api
    restart: always
    network_mode: host
    volumes:
      - ./fim_chat/chat_api/chat.yaml:/app/chat.yaml
    depends_on:
      - postgres
      - redis
      - user_rpc
      - file_rpc

  chat_rpc:
    build:
      context: fim_chat/chat_rpc
    restart: always
    network_mode: host
    volumes:
      - ./fim_chat/chat_rpc/chatrpc.yaml:/app/chatrpc.yaml
    depends_on:
      - postgres

  file_api:
    build:
      context: fim_file/file_api
    restart: always
    network_mode: host
    volumes:
      - ./fim_file/file_api/file.yaml:/app/file.yaml
      - ./fim_file/file_api/uploads:/app/uploads
    depends_on:
      - postgres
      - user_rpc

  file_rpc:
    build:
      context: fim_file/file_rpc
    restart: always
    network_mode: host
    volumes:
      - ./fim_file/file_rpc/filerpc.yaml:/app/filerpc.yaml
    depends_on:
      - postgres

  group_api:
    build:
      context: fim_group/group_api
    restart: always
    network_mode: host
    volumes:
      - ./fim_group/group_api/group.yaml:/app/group.yaml
    depends_on:
      - postgres
      - redis
      - user_rpc
      - group_rpc

  group_rpc:
    build:
      context: fim_group/group_rpc
    restart: always
    network_mode: host
    volumes:
      - ./fim_group/group_rpc/grouprpc.yaml:/app/grouprpc.yaml
    depends_on:
      - postgres
      - redis

  logs_api:
    build:
      context: fim_logs/logs_api
    restart: always
    network_mode: host
    volumes:
      - ./fim_logs/logs_api/logs.yaml:/app/logs.yaml
    depends_on:
      - postgres
      - user_rpc
      - kafka

  settings_api:
    build:
      context: fim_settings/settings_api
    restart: always
    network_mode: host
    volumes:
      - ./fim_settings/settings_api/settings.yaml:/app/settings.yaml
    depends_on:
      - postgres

  settings_rpc:
    build:
      context: fim_settings/settings_rpc
    restart: always
    network_mode: host
    volumes:
      - ./fim_settings/settings_rpc/settingsrpc.yaml:/app/settingsrpc.yaml
    depends_on:
      - postgres

  user_api:
    build:
      context: fim_user/user_api
    restart: always
    network_mode: host
    volumes:
      - ./fim_user/user_api/users.yaml:/app/users.yaml
    depends_on:
      - postgres
      - redis
      - user_rpc
      - chat_rpc
      - group_rpc

  user_rpc:
    build:
      context: fim_user/user_rpc
    restart: always
    network_mode: host
    volumes:
      - ./fim_user/user_rpc/userrpc.yaml:/app/userrpc.yaml
    depends_on:
      - postgres
      - redis

  fim_web:
    image: nginx:alpine
    restart: always
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx/
      - ./fim_web/dist:/usr/share/nginx/fim_web
      - ./nginx/cert/:/usr/share/nginx/cert
